[package]
name = "som"
version = "0.1.0"
authors = ["Sumedhe Dissanayake <sumedhedissanayake@gmail.com>"]
edition = "2018"

[lib]
name = "som"
path = "src/lib.rs"

[[bin]]
name = "som"
path = "src/bin.rs"

[dependencies]
